import { type MigrationInterface, type QueryRunner } from "typeorm";

export class InitialSchema1780058846655 implements MigrationInterface {
    name = 'InitialSchema1780058846655'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "iam_users" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "clerkUserId" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "fullName" character varying(255), "deletedAt" TIMESTAMP WITH TIME ZONE, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_02086c69f80fed8ae319ec498ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_33b21bb98119691bbb789d8010" ON "iam_users" ("clerkUserId") `);
        await queryRunner.query(`CREATE TABLE "iam_settings" ("userId" character varying(26) NOT NULL, "density" character varying(20) NOT NULL DEFAULT 'BALANCED', "locale" character varying(10) NOT NULL DEFAULT 'en-US', "timezone" character varying(50) NOT NULL DEFAULT 'UTC', CONSTRAINT "PK_837562e7d61042e8579f1af3dcb" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TABLE "profile_resume_sources" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "filename" character varying(255) NOT NULL, "contentType" character varying(50) NOT NULL, "blobUri" text NOT NULL, "parseStatus" character varying(20) NOT NULL DEFAULT 'PENDING', "parseError" text, "uploadedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_f3847c4774392e1aca1e5c4f91e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4a3f37c03702fe667ef1db0c17" ON "profile_resume_sources" ("userId") `);
        await queryRunner.query(`CREATE TABLE "profile_profiles" ("userId" character varying(26) NOT NULL, "basicInfo" jsonb, "certifications" jsonb, "lastResumeUploadedAt" TIMESTAMP WITH TIME ZONE, "etag" character varying(64), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_513a121235a77e86cf5137ee663" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TABLE "profile_education" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "school" character varying(255) NOT NULL, "degree" character varying(100), "major" character varying(100), "start" character varying(7), "end" character varying(7), "gpa" character varying(10), "highlights" jsonb, CONSTRAINT "PK_4ee5074ee613d1e0ff7d1750bae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5296a32174641c1db380b0c7ee" ON "profile_education" ("userId") `);
        await queryRunner.query(`CREATE TABLE "profile_work_experiences" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "company" character varying(255) NOT NULL, "title" character varying(255) NOT NULL, "location" character varying(255), "start" character varying(7), "end" character varying(7), "bullets" jsonb, "linkedMaterialIds" jsonb, CONSTRAINT "PK_54cac1aae1de0b9e1322d327dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_88dcee4e8d89ebe3888fb01d6b" ON "profile_work_experiences" ("userId") `);
        await queryRunner.query(`CREATE TABLE "profile_projects" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "start" character varying(7), "end" character varying(7), "linkedMaterialIds" jsonb, CONSTRAINT "PK_d3149ffc17c374c007ccc7fafba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4c1f5bf73dd1dfc2fb9675ecf7" ON "profile_projects" ("userId") `);
        await queryRunner.query(`CREATE TABLE "profile_skills" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "name" character varying(100) NOT NULL, "kind" character varying(20) NOT NULL, CONSTRAINT "PK_9347b76dd1aff0f0285dbba7f79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_19915e8836ec8438a154a7215a" ON "profile_skills" ("userId") `);
        await queryRunner.query(`CREATE TABLE "profile_materials" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "rawText" bytea, "shiningText" text, "rationale" text, "tags" jsonb, "quant" jsonb, "provenanceKind" character varying(20) NOT NULL, "provenanceData" jsonb, "status" character varying(20) NOT NULL DEFAULT 'PROPOSED', "linkedExperienceId" character varying(26), "embedding" jsonb, CONSTRAINT "PK_54ba85d6c64a412590bae6bb061" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a30f796d2af3e1082915a9cc91" ON "profile_materials" ("userId") `);
        await queryRunner.query(`CREATE TABLE "profile_base_resumes" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "name" character varying(100) NOT NULL DEFAULT 'Default', "selectedMaterialIds" jsonb, "isDefault" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_69fb6b68d5f0af61317de1508f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b19bd7b032d8b7f1742c1c4e49" ON "profile_base_resumes" ("userId") `);
        await queryRunner.query(`CREATE TABLE "jobs_captures" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "source" character varying(20) NOT NULL, "sourceUrl" text NOT NULL, "sourceJobId" character varying(100), "capturedHtml" text, "capturedText" text, "meta" jsonb, "capturedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_1d9c4b813cdd619e90271029b0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1fba4258f3904a96522fe28c55" ON "jobs_captures" ("userId") `);
        await queryRunner.query(`CREATE TABLE "jobs_parsed_jds" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "captureId" character varying(26) NOT NULL, "title" character varying(255), "company" character varying(255), "location" character varying(255), "hardSkills" jsonb, "softSkills" jsonb, "experience" jsonb, "educationRequired" jsonb, "hiddenSignals" jsonb, "niceToHave" jsonb, "buzzwordTranslation" text, "parsedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "jdEmbedding" jsonb, CONSTRAINT "PK_03758b01c894f22348fb1a6abf0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_feb810b64cc6262bc5c38195be" ON "jobs_parsed_jds" ("captureId") `);
        await queryRunner.query(`CREATE TABLE "jobs_company_briefs" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "company" character varying(255) NOT NULL, "whatTheyDo" text, "sizeStage" character varying(100), "recentNews" jsonb, "risks" jsonb, "glassdoorRating" double precision, "generatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "ttlExpires" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_2beb09a50858c66a256afa801fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cc34ae7af8c63f31537a77aa0c" ON "jobs_company_briefs" ("company") `);
        await queryRunner.query(`CREATE TABLE "jobs_match_results" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "parsedJdId" character varying(26) NOT NULL, "userId" character varying(26) NOT NULL, "surfaceScore" double precision, "deepScore" double precision, "gaps" jsonb, "hitsSurface" jsonb, "hitsDeep" jsonb, "overallAdvice" character varying(50), "adviceRationale" text, CONSTRAINT "PK_1c7111ca6c84a7e352bc6460a8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3a002fcb4efba17b2ff5939c8a" ON "jobs_match_results" ("parsedJdId") `);
        await queryRunner.query(`CREATE INDEX "IDX_122b60c5adfa76a2fa0141be14" ON "jobs_match_results" ("userId") `);
        await queryRunner.query(`CREATE TABLE "jobs_radar_items" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "captureId" character varying(26), "parsedJdId" character varying(26), "matchId" character varying(26), "resumeSnapshotId" character varying(26), "status" character varying(30) NOT NULL DEFAULT 'BROWSED', "lastStatusAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userDecisionNote" text, CONSTRAINT "PK_b29f4bf2c8cd33bf01c5fffe786" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e7ada921df8d0c0073267e6643" ON "jobs_radar_items" ("userId") `);
        await queryRunner.query(`CREATE TABLE "conv_conversations" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "kind" character varying(30) NOT NULL, "anchorId" character varying(26), "effectiveDensity" character varying(20) NOT NULL DEFAULT 'BALANCED', "lastActivity" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "rollingSummary" text, "importantQuotes" jsonb, CONSTRAINT "PK_9a403e6f7f462d39761dbb193e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1b00eb53aa1ed823bb9dc2fe95" ON "conv_conversations" ("userId") `);
        await queryRunner.query(`CREATE TABLE "conv_messages" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "conversationId" character varying(26) NOT NULL, "role" character varying(20) NOT NULL, "text" text, "toolCalls" jsonb, "toolResult" jsonb, "tokenPrompt" integer, "tokenCompletion" integer, "tokenModel" character varying(50), "tokenCostUsd" double precision, "finishReason" character varying(20), "meta" jsonb, CONSTRAINT "PK_e92ff8a22164eef499dc4496aa9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_57617cae4ce2e769ae633e89fa" ON "conv_messages" ("conversationId") `);
        await queryRunner.query(`CREATE TABLE "tailoring_resumes" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "baseResumeId" character varying(26) NOT NULL, "parsedJdId" character varying(26) NOT NULL, "sections" jsonb, "matchBefore" double precision, "matchAfter" double precision, CONSTRAINT "PK_eca5c946410626de850440abf4b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf1a053e04a0acc15fc6256b47" ON "tailoring_resumes" ("userId") `);
        await queryRunner.query(`CREATE TABLE "tailoring_snapshots" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "tailoredResumeId" character varying(26) NOT NULL, "blobUriPdf" text, "plainText" text, "frozenAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_46aaa492355ac1ef31938f96753" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f35fe30c138aa67526e626997" ON "tailoring_snapshots" ("tailoredResumeId") `);
        await queryRunner.query(`CREATE TABLE "apply_fill_plans" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "radarItemId" character varying(26) NOT NULL, "userId" character varying(26) NOT NULL, "fields" jsonb, "previewSummary" character varying(2000), "userApproved" boolean NOT NULL DEFAULT false, "approvedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_4a3f1f599b45c642bfc96c47162" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f2baa1916de9f9b4cc8fdee33e" ON "apply_fill_plans" ("userId") `);
        await queryRunner.query(`CREATE TABLE "apply_applications" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "radarItemId" character varying(26) NOT NULL, "resumeSnapshotId" character varying(26), "submittedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_31e27c9160641d82686f661deec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9283cf43582e6ae86d560a2ae6" ON "apply_applications" ("userId") `);
        await queryRunner.query(`CREATE TABLE "followup_emails" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "source" character varying(20) NOT NULL DEFAULT 'gmail-web', "subject" character varying(500), "fromAddr" character varying(255), "bodyText" bytea, "kind" character varying(30), "parsed" jsonb, "radarItemId" character varying(26), "receivedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3a02419e4e21acd4b0a04b70f49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dcf9f24db17376bd7bc574e8d2" ON "followup_emails" ("userId") `);
        await queryRunner.query(`CREATE TABLE "followup_drafts" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "emailId" character varying(26) NOT NULL, "userId" character varying(26) NOT NULL, "text" text, "intent" character varying(50), CONSTRAINT "PK_9ca515891639f6bc772ea8e3f57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cd1cd1ecebd998938029383c14" ON "followup_drafts" ("emailId") `);
        await queryRunner.query(`CREATE TABLE "billing_subscriptions" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "tier" character varying(20) NOT NULL DEFAULT 'FREE', "state" character varying(20) NOT NULL DEFAULT 'ACTIVE', "stripeCustomerId" character varying(255), "stripeSubscriptionId" character varying(255), "periodEnd" TIMESTAMP WITH TIME ZONE, "pausedReason" character varying(50), "lastEventId" character varying(255), "lastEventAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_da12bd094f95ed1a9ad21b0b2df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_59e19bfbcc389793e1beee1b84" ON "billing_subscriptions" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_44a362181c5bdbc13fbc16a4df" ON "billing_subscriptions" ("stripeSubscriptionId") `);
        await queryRunner.query(`CREATE TABLE "quota_usage_counters" ("userId" character varying(26) NOT NULL, "tailoringCompleted" integer NOT NULL DEFAULT '0', "tailoringLimit" integer NOT NULL DEFAULT '3', "windowStart" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_a07a690aad6023e5705b5a5f4f0" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TABLE "quota_consume_log" ("id" character varying(26) NOT NULL, "userId" character varying(26) NOT NULL, "tailoredResumeId" character varying(26) NOT NULL, "consumedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_e267746ccd8c5c698be4b87d16a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_55777e3d6da149ce8eddf7c1ff" ON "quota_consume_log" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d98e7e3796b2016351ceea6013" ON "quota_consume_log" ("tailoredResumeId") `);
        await queryRunner.query(`CREATE TABLE "reco_recommendations" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "items" jsonb, "sentAt" TIMESTAMP WITH TIME ZONE, "feedback" jsonb, CONSTRAINT "PK_2e76d648b6aeea78f5788f2a846" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aa652bfba5639fbf8be0385865" ON "reco_recommendations" ("userId") `);
        await queryRunner.query(`CREATE TABLE "telemetry_events" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "eventType" character varying(100) NOT NULL, "userId" character varying(26), "payload" jsonb, CONSTRAINT "PK_17996ee1fa9a5ce42e7ffaa8c68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f2c13bde4aec24fa23351c012" ON "telemetry_events" ("userId") `);
        await queryRunner.query(`CREATE TABLE "outbox_events" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "eventType" character varying(100) NOT NULL, "payload" jsonb, "consumerGroup" character varying(50) NOT NULL, "dispatchedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6689a16c00d09b8089f6237f1d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40309f788055cd517e68f22958" ON "outbox_events" ("consumerGroup") `);
        await queryRunner.query(`CREATE TABLE "idempotency_keys" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "userId" character varying(26) NOT NULL, "key" character varying(255) NOT NULL, "statusCode" integer NOT NULL, "responseBody" jsonb, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_8ad20779ad0411107a56e53d0f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a3aaa526470ebb79221693d32" ON "idempotency_keys" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0afd83cbf08c9d12089a9bffc5" ON "idempotency_keys" ("key") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_0afd83cbf08c9d12089a9bffc5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a3aaa526470ebb79221693d32"`);
        await queryRunner.query(`DROP TABLE "idempotency_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40309f788055cd517e68f22958"`);
        await queryRunner.query(`DROP TABLE "outbox_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f2c13bde4aec24fa23351c012"`);
        await queryRunner.query(`DROP TABLE "telemetry_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa652bfba5639fbf8be0385865"`);
        await queryRunner.query(`DROP TABLE "reco_recommendations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d98e7e3796b2016351ceea6013"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55777e3d6da149ce8eddf7c1ff"`);
        await queryRunner.query(`DROP TABLE "quota_consume_log"`);
        await queryRunner.query(`DROP TABLE "quota_usage_counters"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44a362181c5bdbc13fbc16a4df"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59e19bfbcc389793e1beee1b84"`);
        await queryRunner.query(`DROP TABLE "billing_subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd1cd1ecebd998938029383c14"`);
        await queryRunner.query(`DROP TABLE "followup_drafts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcf9f24db17376bd7bc574e8d2"`);
        await queryRunner.query(`DROP TABLE "followup_emails"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9283cf43582e6ae86d560a2ae6"`);
        await queryRunner.query(`DROP TABLE "apply_applications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2baa1916de9f9b4cc8fdee33e"`);
        await queryRunner.query(`DROP TABLE "apply_fill_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f35fe30c138aa67526e626997"`);
        await queryRunner.query(`DROP TABLE "tailoring_snapshots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf1a053e04a0acc15fc6256b47"`);
        await queryRunner.query(`DROP TABLE "tailoring_resumes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57617cae4ce2e769ae633e89fa"`);
        await queryRunner.query(`DROP TABLE "conv_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b00eb53aa1ed823bb9dc2fe95"`);
        await queryRunner.query(`DROP TABLE "conv_conversations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7ada921df8d0c0073267e6643"`);
        await queryRunner.query(`DROP TABLE "jobs_radar_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_122b60c5adfa76a2fa0141be14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a002fcb4efba17b2ff5939c8a"`);
        await queryRunner.query(`DROP TABLE "jobs_match_results"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc34ae7af8c63f31537a77aa0c"`);
        await queryRunner.query(`DROP TABLE "jobs_company_briefs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_feb810b64cc6262bc5c38195be"`);
        await queryRunner.query(`DROP TABLE "jobs_parsed_jds"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fba4258f3904a96522fe28c55"`);
        await queryRunner.query(`DROP TABLE "jobs_captures"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b19bd7b032d8b7f1742c1c4e49"`);
        await queryRunner.query(`DROP TABLE "profile_base_resumes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a30f796d2af3e1082915a9cc91"`);
        await queryRunner.query(`DROP TABLE "profile_materials"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19915e8836ec8438a154a7215a"`);
        await queryRunner.query(`DROP TABLE "profile_skills"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c1f5bf73dd1dfc2fb9675ecf7"`);
        await queryRunner.query(`DROP TABLE "profile_projects"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88dcee4e8d89ebe3888fb01d6b"`);
        await queryRunner.query(`DROP TABLE "profile_work_experiences"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5296a32174641c1db380b0c7ee"`);
        await queryRunner.query(`DROP TABLE "profile_education"`);
        await queryRunner.query(`DROP TABLE "profile_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a3f37c03702fe667ef1db0c17"`);
        await queryRunner.query(`DROP TABLE "profile_resume_sources"`);
        await queryRunner.query(`DROP TABLE "iam_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33b21bb98119691bbb789d8010"`);
        await queryRunner.query(`DROP TABLE "iam_users"`);
    }

}
